# Generated by Django 4.2.1 on 2024-04-11 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitlinkr_app', '0002_fitlinkruser_role_workout_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='available_spots',
        ),
    ]
